### ISSUE TITLE
挂单失败，重新挂单中... TypeError: Cannot read properties of undefined (reading 'available')

### ISSUE THREAD

**Issue by 350887156** [catsats/backpack_exchange#1]
挂单失败，重新挂单中... TypeError: Cannot read properties of undefined (reading 'available')

**Comment by flykye** [comment]
一样的错误

**Comment by catsats** [comment]
卖出失败价格变动原因 因为是限定单价，每次发请求都挂单， 三秒过后没交易成功就取消挂单再重新挂单 一直循环 这样就能做到卖出和买入价格波动不大，甚至一模一样

**Comment by catsats** [comment]
挂单失败，重新挂单中 是正常的

**Comment by flykye** [comment]
> 一样的错误

<img width="581" alt="image" src="https://github.com/catsats/backpack_exchange/assets/236068/8e607a8d-7380-4d7d-8c8b-979bb99fcdd5">
我的挂单失败是因为钱包里面没有USDC，导致运行错误了。
